package ro.mpp2025.network.rpcprotocol;

public enum RequestType {
    LOGIN_TESTER,
    LOGIN_PROGRAMMER,
    ADD_TESTER,
    UPDATE_TESTER,
    GET_TESTERS,
    DELETE_TESTER,
    FIND_BY_EMAIL_TESTER,
    LOGOUT_TESTER,
    LOGOUT_PROGRAMMER,
    ADD_PROGRAMMER,
    UPDATE_PROGRAMMER,
    DELETE_PROGRAMMER,
    FIND_BY_EMAIL_PROGRAMMER,
    GET_PROGRAMMERS,
    FIND_BY_EMAIL_ADMIN,
    ADD_BUG,
    DELETE_BUG,
    UPDATE_BUG,
    GET_BUGS, FIND_BY_NAME_BUG, LOGIN_ADMIN, LOGOUT_ADMIN,
}
